<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(BibTfm)</TargetFramework>
    <RootNamespace>Bibliotaph.Spike.WorkerHost</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Spike.Contracts\Spike.Contracts.csproj" />
  </ItemGroup>
</Project>
