using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

// Converts Lucide's 24x24 stroke icons into WPF path mini-language, one Geometry resource per icon.
// WPF's parser is stricter than SVG's (it rejects packed arc flags such as "a2 2 0 012 2"), and it has
// no rect or circle elements, so every shape is rewritten as explicit path commands.

var repo = FindRepoRoot();
var sourceDir = Path.Combine(repo, "tools", "IconGen", "lucide");
var outputDir = Path.Combine(repo, "src", "Bibliotaph.App", "Icons");
Directory.CreateDirectory(outputDir);

var version = "unknown";
var resources = new StringBuilder();
foreach (var file in Directory.GetFiles(sourceDir, "*.svg").Order(StringComparer.Ordinal))
{
    var text = File.ReadAllText(file);
    var match = Regex.Match(text, @"lucide-static v([\d.]+)");
    if (match.Success) version = match.Groups[1].Value;

    var svg = XElement.Parse(Regex.Replace(text, "<!--.*?-->", "", RegexOptions.Singleline));
    var data = string.Join(" ", svg.Elements().Select(ToPathData));
    var key = "Icon." + string.Concat(Path.GetFileNameWithoutExtension(file).Split('-').Select(p => char.ToUpperInvariant(p[0]) + p[1..]));
    resources.AppendLine(CultureInfo.InvariantCulture, $"  <Geometry x:Key=\"{key}\">{data}</Geometry>");
}

var xaml = $"""
    <!--
      Generated by tools/IconGen from Lucide {version} (lucide-static). Do not edit by hand.
      Lucide is ISC licensed; see LICENSE-lucide.txt. Each geometry is in Lucide's 24x24 space,
      drawn as strokes by the LucideIcon control.
    -->
    <ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    {resources.ToString().TrimEnd()}
    </ResourceDictionary>

    """;
File.WriteAllText(Path.Combine(outputDir, "Icons.xaml"), xaml.ReplaceLineEndings("\r\n"));
File.Copy(Path.Combine(sourceDir, "LICENSE"), Path.Combine(outputDir, "LICENSE-lucide.txt"), overwrite: true);
Console.WriteLine($"Wrote {Directory.GetFiles(sourceDir, "*.svg").Length} icons from Lucide {version} to {outputDir}");
return 0;

static string FindRepoRoot()
{
    for (var dir = new DirectoryInfo(AppContext.BaseDirectory); dir is not null; dir = dir.Parent)
        if (File.Exists(Path.Combine(dir.FullName, "Bibliotaph.slnx"))) return dir.FullName;
    throw new InvalidOperationException("Run IconGen from inside the Bibliotaph repository.");
}

static string ToPathData(XElement e)
{
    double A(string name, double fallback = 0) =>
        e.Attribute(name) is { } a ? double.Parse(a.Value, CultureInfo.InvariantCulture) : fallback;

    return e.Name.LocalName switch
    {
        "path" => PathData.Normalize(e.Attribute("d")!.Value),
        "line" => Fmt($"M {A("x1")} {A("y1")} L {A("x2")} {A("y2")}"),
        "polyline" => Poly(e.Attribute("points")!.Value, close: false),
        "polygon" => Poly(e.Attribute("points")!.Value, close: true),
        "circle" => Ellipse(A("cx"), A("cy"), A("r"), A("r")),
        "ellipse" => Ellipse(A("cx"), A("cy"), A("rx"), A("ry")),
        "rect" => Rect(A("x"), A("y"), A("width"), A("height"), A("rx", A("ry")), A("ry", A("rx"))),
        var other => throw new NotSupportedException($"SVG element <{other}> is not supported."),
    };
}

static string Poly(string points, bool close)
{
    var n = PathData.Numbers(points).ToList();
    var sb = new StringBuilder(Fmt($"M {n[0]} {n[1]}"));
    for (var i = 2; i + 1 < n.Count; i += 2) sb.Append(Fmt($" L {n[i]} {n[i + 1]}"));
    if (close) sb.Append(" Z");
    return sb.ToString();
}

static string Ellipse(double cx, double cy, double rx, double ry) =>
    Fmt($"M {cx - rx} {cy} A {rx} {ry} 0 1 0 {cx + rx} {cy} A {rx} {ry} 0 1 0 {cx - rx} {cy} Z");

static string Rect(double x, double y, double w, double h, double rx, double ry)
{
    rx = Math.Min(rx, w / 2);
    ry = Math.Min(ry, h / 2);
    if (rx <= 0 || ry <= 0) return Fmt($"M {x} {y} H {x + w} V {y + h} H {x} Z");
    return Fmt($"M {x + rx} {y} H {x + w - rx} A {rx} {ry} 0 0 1 {x + w} {y + ry} V {y + h - ry} ") +
           Fmt($"A {rx} {ry} 0 0 1 {x + w - rx} {y + h} H {x + rx} A {rx} {ry} 0 0 1 {x} {y + h - ry} ") +
           Fmt($"V {y + ry} A {rx} {ry} 0 0 1 {x + rx} {y} Z");
}

static string Fmt(FormattableString s) => s.ToString(CultureInfo.InvariantCulture);

static class PathData
{
    static readonly Regex Token = new(@"[MmZzLlHhVvCcSsQqTtAa]|[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?", RegexOptions.Compiled);

    public static IEnumerable<double> Numbers(string s) =>
        Token.Matches(s).Select(m => double.Parse(m.Value, CultureInfo.InvariantCulture));

    static int Arity(char command) => char.ToUpperInvariant(command) switch
    {
        'Z' => 0,
        'H' or 'V' => 1,
        'M' or 'L' or 'T' => 2,
        'S' or 'Q' => 4,
        'C' => 6,
        'A' => 7,
        _ => throw new FormatException($"Unknown path command {command}."),
    };

    /// <summary>Re-emits SVG path data with every command explicit and every number separated.</summary>
    public static string Normalize(string d)
    {
        var output = new List<string>();
        var i = 0;
        char command = ' ';
        while (true)
        {
            SkipSeparators(d, ref i);
            if (i >= d.Length) break;
            if (char.IsLetter(d[i]))
            {
                command = d[i++];
                if (Arity(command) == 0)
                {
                    output.Add("Z");
                    continue;
                }
            }
            else if (command == ' ')
            {
                throw new FormatException($"Path data must start with a command: {d}");
            }

            var args = new string[Arity(command)];
            for (var a = 0; a < args.Length; a++)
            {
                SkipSeparators(d, ref i);
                // Arc flags are single digits and may be packed against the next number.
                args[a] = char.ToUpperInvariant(command) == 'A' && a is 3 or 4 ? d[i++].ToString() : ReadNumber(d, ref i);
            }
            // A relative moveto that starts a path is absolute (SVG 9.3.3). Paths are concatenated
            // here, so make that explicit or it would become relative to the previous element.
            var emitted = output.Count == 0 && command == 'm' ? 'M' : command;
            output.Add(emitted + " " + string.Join(" ", args));

            // Extra coordinate pairs after a moveto are implicit linetos.
            if (command == 'M') command = 'L';
            else if (command == 'm') command = 'l';
        }
        return string.Join(" ", output);
    }

    static void SkipSeparators(string d, ref int i)
    {
        while (i < d.Length && (char.IsWhiteSpace(d[i]) || d[i] == ',')) i++;
    }

    static string ReadNumber(string d, ref int i)
    {
        var m = Token.Match(d, i);
        if (!m.Success || m.Index != i || char.IsLetter(m.Value[0])) throw new FormatException($"Expected a number at {i} in: {d}");
        i += m.Length;
        return double.Parse(m.Value, CultureInfo.InvariantCulture).ToString("R", CultureInfo.InvariantCulture);
    }
}
