// <auto-generated />
using System;
using Bibliotaph.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bibliotaph.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261008172504_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Assertion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<string>("EvidencePagesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_pages_json");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_json");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Field", "State");

                    b.ToTable("assertion");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("format");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("page_count");

                    b.Property<long?>("PreviousVersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_version_id");

                    b.Property<string>("Protection")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protection");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("PreviousVersionId");

                    b.ToTable("document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.FileLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_utc");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_utc");

                    b.Property<string>("NtfsFileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ntfs_file_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<long>("SourceRootId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_root_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SourceRootId", "RelativePath")
                        .IsUnique();

                    b.ToTable("file_location");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.PageRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<int>("FirstPdfPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_pdf_page");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_stale");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("LastPdfPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_pdf_page");

                    b.Property<string>("PrintedLabels")
                        .HasColumnType("TEXT")
                        .HasColumnName("printed_labels");

                    b.Property<string>("TextFingerprint")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_fingerprint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("page_ref");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("setting");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.SourceRoot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_utc");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("VolumeSerial")
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_serial");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("source_root");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Assertion", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany("Assertions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "PreviousVersion")
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.FileLocation", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany("Locations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bibliotaph.Catalog.Entities.SourceRoot", "SourceRoot")
                        .WithMany("Files")
                        .HasForeignKey("SourceRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("SourceRoot");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.PageRef", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany("PageRefs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
                {
                    b.Navigation("Assertions");

                    b.Navigation("Locations");

                    b.Navigation("PageRefs");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.SourceRoot", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
