// <auto-generated />
using System;
using Bibliotaph.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bibliotaph.Catalog.Migrations;

[DbContext(typeof(CatalogDbContext))]
[Migration("20261010162053_CatalogForgetText")]
partial class CatalogForgetText
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "11.0.0-rc.1.26425.128");

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Assertion", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("ContentHash")
                    .HasColumnType("TEXT")
                    .HasColumnName("content_hash");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<DateTime?>("DecidedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("decided_utc");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<string>("EvidencePagesJson")
                    .HasColumnType("TEXT")
                    .HasColumnName("evidence_pages_json");

                b.Property<string>("EvidenceQuote")
                    .HasColumnType("TEXT")
                    .HasColumnName("evidence_quote");

                b.Property<string>("Field")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("field");

                b.Property<bool>("FromSampling")
                    .HasColumnType("INTEGER")
                    .HasColumnName("from_sampling");

                b.Property<string>("NormalizedValue")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("normalized_value");

                b.Property<string>("Origin")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("origin");

                b.Property<string>("RunId")
                    .HasColumnType("TEXT")
                    .HasColumnName("run_id");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("state");

                b.Property<string>("ValueJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("value_json");

                b.HasKey("Id");

                b.HasIndex("EntryId", "Field", "State");

                b.ToTable("assertion");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.ClassificationRun", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("ContentHash")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("content_hash");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<DateTime?>("FinishedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("finished_utc");

                b.Property<string>("Model")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("model");

                b.Property<string>("Outcome")
                    .HasColumnType("TEXT")
                    .HasColumnName("outcome");

                b.Property<string>("PagesJson")
                    .HasColumnType("TEXT")
                    .HasColumnName("pages_json");

                b.Property<int>("PromptVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("prompt_version");

                b.Property<string>("Provider")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("provider");

                b.Property<int>("SchemaVersion")
                    .HasColumnType("INTEGER")
                    .HasColumnName("schema_version");

                b.Property<DateTime>("StartedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("started_utc");

                b.HasKey("Id");

                b.HasIndex("EntryId");

                b.HasIndex("ContentHash", "Model", "PromptVersion");

                b.ToTable("classification_run");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.CollectionItem", b =>
            {
                b.Property<long>("CollectionId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("collection_id");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<DateTime>("AddedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("added_utc");

                b.HasKey("CollectionId", "EntryId");

                b.HasIndex("EntryId");

                b.ToTable("collection_item");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.CollectionNode", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<string>("Description")
                    .HasColumnType("TEXT")
                    .HasColumnName("description");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("name");

                b.Property<long?>("ParentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("parent_id");

                b.Property<bool>("Pinned")
                    .HasColumnType("INTEGER")
                    .HasColumnName("pinned");

                b.Property<DateTime>("UsedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("used_utc");

                b.HasKey("Id");

                b.HasIndex("ParentId");

                b.ToTable("collection");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.CopyDecision", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("Answer")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("answer");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<string>("FirstHash")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("first_hash");

                b.Property<string>("SecondHash")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("second_hash");

                b.HasKey("Id");

                b.HasIndex("FirstHash", "SecondHash")
                    .IsUnique();

                b.ToTable("copy_decision");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("CapabilitiesJson")
                    .HasColumnType("TEXT")
                    .HasColumnName("capabilities_json");

                b.Property<string>("ContentHash")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("content_hash");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<string>("Format")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("format");

                b.Property<int?>("PageCount")
                    .HasColumnType("INTEGER")
                    .HasColumnName("page_count");

                b.Property<string>("Protection")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("protection");

                b.Property<DateTime?>("TextForgottenUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("text_forgotten_utc");

                b.HasKey("Id");

                b.HasIndex("ContentHash")
                    .IsUnique();

                b.ToTable("document");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.ElsewhereMatch", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("Answer")
                    .HasColumnType("TEXT")
                    .HasColumnName("answer");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<long>("DocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("document_id");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.HasKey("Id");

                b.HasIndex("DocumentId");

                b.HasIndex("EntryId", "DocumentId")
                    .IsUnique();

                b.ToTable("elsewhere_match");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Entry", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<string>("Kind")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("kind");

                b.Property<long?>("MergedIntoEntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("merged_into_entry_id");

                b.Property<long?>("ParentEntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("parent_entry_id");

                b.HasKey("Id");

                b.HasIndex("MergedIntoEntryId");

                b.HasIndex("ParentEntryId");

                b.ToTable("entry");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.EntryJoin", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<long>("DocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("document_id");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<long>("JoinedEntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("joined_entry_id");

                b.Property<long>("MatchedDocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("matched_document_id");

                b.Property<string>("MovedJson")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("moved_json");

                b.HasKey("Id");

                b.HasIndex("DocumentId");

                b.HasIndex("EntryId");

                b.HasIndex("JoinedEntryId");

                b.HasIndex("MatchedDocumentId");

                b.ToTable("entry_join");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.EntrySource", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<long>("DocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("document_id");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<int?>("FirstPdfPage")
                    .HasColumnType("INTEGER")
                    .HasColumnName("first_pdf_page");

                b.Property<bool>("IsCurrent")
                    .HasColumnType("INTEGER")
                    .HasColumnName("is_current");

                b.Property<int?>("LastPdfPage")
                    .HasColumnType("INTEGER")
                    .HasColumnName("last_pdf_page");

                b.HasKey("Id");

                b.HasIndex("DocumentId")
                    .IsUnique()
                    .HasDatabaseName("ix_entry_source_whole")
                    .HasFilter("first_pdf_page IS NULL");

                b.HasIndex("EntryId")
                    .IsUnique()
                    .HasDatabaseName("ix_entry_source_current")
                    .HasFilter("is_current = 1");

                b.HasIndex("DocumentId", "EntryId");

                b.ToTable("entry_source");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Favorite", b =>
            {
                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.HasKey("EntryId");

                b.ToTable("favorite");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.FileLocation", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<long?>("ContainerId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("container_id");

                b.Property<string>("ContentHash")
                    .HasColumnType("TEXT")
                    .HasColumnName("content_hash");

                b.Property<long?>("DocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("document_id");

                b.Property<long?>("EntryCrc32")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_crc32");

                b.Property<string>("EntryPath")
                    .HasColumnType("TEXT")
                    .HasColumnName("entry_path");

                b.Property<DateTime>("LastSeenUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("last_seen_utc");

                b.Property<DateTime>("ModifiedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("modified_utc");

                b.Property<string>("NtfsFileId")
                    .HasColumnType("TEXT")
                    .HasColumnName("ntfs_file_id");

                b.Property<long?>("PreviousDocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("previous_document_id");

                b.Property<string>("Problem")
                    .HasColumnType("TEXT")
                    .HasColumnName("problem");

                b.Property<string>("RelativePath")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("relative_path");

                b.Property<long>("SizeBytes")
                    .HasColumnType("INTEGER")
                    .HasColumnName("size_bytes");

                b.Property<long>("SourceRootId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("source_root_id");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("state");

                b.HasKey("Id");

                b.HasIndex("ContainerId");

                b.HasIndex("ContentHash");

                b.HasIndex("DocumentId");

                b.HasIndex("PreviousDocumentId");

                b.HasIndex("SourceRootId", "RelativePath")
                    .IsUnique();

                b.ToTable("file_location");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.IgnoredFolderLabel", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<string>("Folder")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("folder");

                b.Property<string>("TermKey")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("term_key");

                b.Property<string>("Vocabulary")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("vocabulary");

                b.HasKey("Id");

                b.HasIndex("Folder", "Vocabulary", "TermKey")
                    .IsUnique();

                b.ToTable("ignored_folder_label");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Note", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<long?>("PageRefId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("page_ref_id");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("text");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("updated_utc");

                b.HasKey("Id");

                b.HasIndex("EntryId")
                    .IsUnique()
                    .HasDatabaseName("ix_note_entry_own")
                    .HasFilter("page_ref_id IS NULL");

                b.HasIndex("PageRefId");

                b.HasIndex("EntryId", "PageRefId");

                b.ToTable("note");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.PackDecision", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("Answer")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("answer");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<string>("FolderPath")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("folder_path");

                b.Property<bool>("IsArchive")
                    .HasColumnType("INTEGER")
                    .HasColumnName("is_archive");

                b.Property<long>("SourceRootId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("source_root_id");

                b.HasKey("Id");

                b.HasIndex("EntryId")
                    .IsUnique();

                b.HasIndex("SourceRootId", "FolderPath")
                    .IsUnique();

                b.ToTable("pack_decision");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.PageRef", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("Check")
                    .HasColumnType("TEXT")
                    .HasColumnName("check");

                b.Property<long?>("CheckDocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("check_document_id");

                b.Property<int?>("CheckFirstPdfPage")
                    .HasColumnType("INTEGER")
                    .HasColumnName("check_first_pdf_page");

                b.Property<int?>("CheckLastPdfPage")
                    .HasColumnType("INTEGER")
                    .HasColumnName("check_last_pdf_page");

                b.Property<long>("DocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("document_id");

                b.Property<string>("FirstFingerprint")
                    .HasColumnType("TEXT")
                    .HasColumnName("first_fingerprint");

                b.Property<string>("FirstLabel")
                    .HasColumnType("TEXT")
                    .HasColumnName("first_label");

                b.Property<int>("FirstPdfPage")
                    .HasColumnType("INTEGER")
                    .HasColumnName("first_pdf_page");

                b.Property<string>("LastFingerprint")
                    .HasColumnType("TEXT")
                    .HasColumnName("last_fingerprint");

                b.Property<string>("LastLabel")
                    .HasColumnType("TEXT")
                    .HasColumnName("last_label");

                b.Property<int>("LastPdfPage")
                    .HasColumnType("INTEGER")
                    .HasColumnName("last_pdf_page");

                b.HasKey("Id");

                b.HasIndex("CheckDocumentId");

                b.HasIndex("DocumentId");

                b.ToTable("page_ref");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.ReadingState", b =>
            {
                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<long>("DocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("document_id");

                b.Property<DateTime>("OpenedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("opened_utc");

                b.Property<int>("PageIndex")
                    .HasColumnType("INTEGER")
                    .HasColumnName("page_index");

                b.HasKey("EntryId");

                b.HasIndex("DocumentId");

                b.HasIndex("OpenedUtc");

                b.ToTable("reading_state");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Rejection", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<string>("Field")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("field");

                b.Property<string>("NormalizedValue")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("normalized_value");

                b.HasKey("Id");

                b.HasIndex("EntryId", "Field", "NormalizedValue")
                    .IsUnique();

                b.ToTable("rejection");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SessionItem", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("AddedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("added_utc");

                b.Property<long>("EntryId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("entry_id");

                b.Property<string>("Label")
                    .HasColumnType("TEXT")
                    .HasColumnName("label");

                b.Property<string>("Note")
                    .HasColumnType("TEXT")
                    .HasColumnName("note");

                b.Property<long>("PackId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("pack_id");

                b.Property<long?>("PageRefId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("page_ref_id");

                b.Property<int>("Position")
                    .HasColumnType("INTEGER")
                    .HasColumnName("position");

                b.Property<long?>("SectionId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("section_id");

                b.HasKey("Id");

                b.HasIndex("EntryId");

                b.HasIndex("PackId");

                b.HasIndex("PageRefId");

                b.HasIndex("SectionId");

                b.ToTable("session_item");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SessionPack", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<DateOnly?>("Date")
                    .HasColumnType("TEXT")
                    .HasColumnName("date");

                b.Property<string>("Notes")
                    .HasColumnType("TEXT")
                    .HasColumnName("notes");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("title");

                b.Property<DateTime>("TouchedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("touched_utc");

                b.HasKey("Id");

                b.HasIndex("TouchedUtc");

                b.ToTable("session_pack");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SessionSection", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("name");

                b.Property<long>("PackId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("pack_id");

                b.Property<int>("Position")
                    .HasColumnType("INTEGER")
                    .HasColumnName("position");

                b.HasKey("Id");

                b.HasIndex("PackId");

                b.ToTable("session_section");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Setting", b =>
            {
                b.Property<string>("Key")
                    .HasColumnType("TEXT")
                    .HasColumnName("key");

                b.Property<string>("Value")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("value");

                b.HasKey("Key");

                b.ToTable("setting");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SmartView", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<string>("Definition")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("definition");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("name");

                b.Property<DateTime>("UpdatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("updated_utc");

                b.HasKey("Id");

                b.HasIndex("Name");

                b.ToTable("smart_view");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SourceRoot", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("AddedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("added_utc");

                b.Property<string>("Availability")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("availability");

                b.Property<string>("Path")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("path");

                b.Property<string>("VolumeSerial")
                    .HasColumnType("TEXT")
                    .HasColumnName("volume_serial");

                b.HasKey("Id");

                b.HasIndex("Path")
                    .IsUnique();

                b.ToTable("source_root");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.VersionProposal", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<int>("ComparedPages")
                    .HasColumnType("INTEGER")
                    .HasColumnName("compared_pages");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<long>("DocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("document_id");

                b.Property<string>("Evidence")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("evidence");

                b.Property<long>("MatchedDocumentId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("matched_document_id");

                b.Property<int>("SharedPages")
                    .HasColumnType("INTEGER")
                    .HasColumnName("shared_pages");

                b.HasKey("Id");

                b.HasIndex("DocumentId")
                    .IsUnique();

                b.HasIndex("MatchedDocumentId");

                b.ToTable("version_proposal");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyAlias", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<string>("Normalized")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("normalized");

                b.Property<long>("TermId")
                    .HasColumnType("INTEGER")
                    .HasColumnName("term_id");

                b.Property<string>("Text")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("text");

                b.HasKey("Id");

                b.HasIndex("TermId", "Normalized")
                    .IsUnique();

                b.ToTable("vocabulary_alias");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyTerm", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_utc");

                b.Property<string>("Key")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("key");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("label");

                b.Property<string>("Origin")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("origin");

                b.Property<string>("ParentKey")
                    .HasColumnType("TEXT")
                    .HasColumnName("parent_key");

                b.Property<string>("ShortLabel")
                    .HasColumnType("TEXT")
                    .HasColumnName("short_label");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("state");

                b.Property<string>("Vocabulary")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("vocabulary");

                b.HasKey("Id");

                b.HasIndex("Vocabulary", "Key")
                    .IsUnique();

                b.ToTable("vocabulary_term");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Assertion", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", "Entry")
                    .WithMany("Assertions")
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Entry");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.ClassificationRun", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", "Entry")
                    .WithMany()
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Entry");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.CollectionItem", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.CollectionNode", null)
                    .WithMany()
                    .HasForeignKey("CollectionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.CollectionNode", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.CollectionNode", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.ElsewhereMatch", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Entry", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("MergedIntoEntryId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Bibliotaph.Catalog.Entities.Entry", "ParentEntry")
                    .WithMany()
                    .HasForeignKey("ParentEntryId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.Navigation("ParentEntry");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.EntryJoin", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("JoinedEntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("MatchedDocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.EntrySource", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                    .WithMany("Sources")
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Entry", "Entry")
                    .WithMany("Sources")
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Document");

                b.Navigation("Entry");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Favorite", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithOne()
                    .HasForeignKey("Bibliotaph.Catalog.Entities.Favorite", "EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.FileLocation", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.FileLocation", "Container")
                    .WithMany()
                    .HasForeignKey("ContainerId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                    .WithMany("Locations")
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("PreviousDocumentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Bibliotaph.Catalog.Entities.SourceRoot", "SourceRoot")
                    .WithMany("Files")
                    .HasForeignKey("SourceRootId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Container");

                b.Navigation("Document");

                b.Navigation("SourceRoot");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Note", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.PageRef", "PageRef")
                    .WithMany()
                    .HasForeignKey("PageRefId")
                    .OnDelete(DeleteBehavior.Cascade);

                b.Navigation("PageRef");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.PackDecision", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.SourceRoot", null)
                    .WithMany()
                    .HasForeignKey("SourceRootId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.PageRef", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("CheckDocumentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                    .WithMany("PageRefs")
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Document");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.ReadingState", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithOne()
                    .HasForeignKey("Bibliotaph.Catalog.Entities.ReadingState", "EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Rejection", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", "Entry")
                    .WithMany("Rejections")
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Entry");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SessionItem", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Entry", null)
                    .WithMany()
                    .HasForeignKey("EntryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.SessionPack", null)
                    .WithMany()
                    .HasForeignKey("PackId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.PageRef", "PageRef")
                    .WithMany()
                    .HasForeignKey("PageRefId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("Bibliotaph.Catalog.Entities.SessionSection", null)
                    .WithMany()
                    .HasForeignKey("SectionId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("PageRef");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SessionSection", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.SessionPack", null)
                    .WithMany()
                    .HasForeignKey("PackId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.VersionProposal", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bibliotaph.Catalog.Entities.Document", null)
                    .WithMany()
                    .HasForeignKey("MatchedDocumentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyAlias", b =>
            {
                b.HasOne("Bibliotaph.Catalog.Entities.VocabularyTerm", "Term")
                    .WithMany("Aliases")
                    .HasForeignKey("TermId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Term");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
            {
                b.Navigation("Locations");

                b.Navigation("PageRefs");

                b.Navigation("Sources");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.Entry", b =>
            {
                b.Navigation("Assertions");

                b.Navigation("Rejections");

                b.Navigation("Sources");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.SourceRoot", b =>
            {
                b.Navigation("Files");
            });

        modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyTerm", b =>
            {
                b.Navigation("Aliases");
            });
#pragma warning restore 612, 618
    }
}
