// <auto-generated />
using System;
using Bibliotaph.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bibliotaph.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Assertion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<DateTime?>("DecidedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_utc");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<string>("EvidencePagesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_pages_json");

                    b.Property<string>("EvidenceQuote")
                        .HasColumnType("TEXT")
                        .HasColumnName("evidence_quote");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field");

                    b.Property<bool>("FromSampling")
                        .HasColumnType("INTEGER")
                        .HasColumnName("from_sampling");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_value");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<string>("RunId")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_json");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Field", "State");

                    b.ToTable("assertion");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.ClassificationRun", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("finished_utc");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("PagesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("pages_json");

                    b.Property<int>("PromptVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("provider");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schema_version");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ContentHash", "Model", "PromptVersion");

                    b.ToTable("classification_run");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("capabilities_json");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("format");

                    b.Property<int?>("PageCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("page_count");

                    b.Property<long?>("PreviousVersionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("previous_version_id");

                    b.Property<string>("Protection")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protection");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique();

                    b.HasIndex("PreviousVersionId");

                    b.ToTable("document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.FileLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("content_hash");

                    b.Property<long?>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_utc");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified_utc");

                    b.Property<string>("NtfsFileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ntfs_file_id");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size_bytes");

                    b.Property<long>("SourceRootId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_root_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("DocumentId");

                    b.HasIndex("SourceRootId", "RelativePath")
                        .IsUnique();

                    b.ToTable("file_location");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.IgnoredFolderLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("folder");

                    b.Property<string>("TermKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("term_key");

                    b.Property<string>("Vocabulary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vocabulary");

                    b.HasKey("Id");

                    b.HasIndex("Folder", "Vocabulary", "TermKey")
                        .IsUnique();

                    b.ToTable("ignored_folder_label");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.PageRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<int>("FirstPdfPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_pdf_page");

                    b.Property<bool>("IsStale")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_stale");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<int>("LastPdfPage")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_pdf_page");

                    b.Property<string>("PrintedLabels")
                        .HasColumnType("TEXT")
                        .HasColumnName("printed_labels");

                    b.Property<string>("TextFingerprint")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_fingerprint");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("page_ref");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Rejection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<long>("DocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized_value");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Field", "NormalizedValue")
                        .IsUnique();

                    b.ToTable("rejection");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("setting");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.SourceRoot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_utc");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("VolumeSerial")
                        .HasColumnType("TEXT")
                        .HasColumnName("volume_serial");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("source_root");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyAlias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Normalized")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("normalized");

                    b.Property<long>("TermId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("term_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "Normalized")
                        .IsUnique();

                    b.ToTable("vocabulary_alias");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyTerm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_utc");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("origin");

                    b.Property<string>("ParentKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_key");

                    b.Property<string>("ShortLabel")
                        .HasColumnType("TEXT")
                        .HasColumnName("short_label");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<string>("Vocabulary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("vocabulary");

                    b.HasKey("Id");

                    b.HasIndex("Vocabulary", "Key")
                        .IsUnique();

                    b.ToTable("vocabulary_term");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Assertion", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany("Assertions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.ClassificationRun", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "PreviousVersion")
                        .WithMany()
                        .HasForeignKey("PreviousVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PreviousVersion");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.FileLocation", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany("Locations")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bibliotaph.Catalog.Entities.SourceRoot", "SourceRoot")
                        .WithMany("Files")
                        .HasForeignKey("SourceRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("SourceRoot");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.PageRef", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany("PageRefs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Rejection", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.Document", "Document")
                        .WithMany("Rejections")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyAlias", b =>
                {
                    b.HasOne("Bibliotaph.Catalog.Entities.VocabularyTerm", "Term")
                        .WithMany("Aliases")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.Document", b =>
                {
                    b.Navigation("Assertions");

                    b.Navigation("Locations");

                    b.Navigation("PageRefs");

                    b.Navigation("Rejections");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.SourceRoot", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("Bibliotaph.Catalog.Entities.VocabularyTerm", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
